name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install PlatformIO
      run: |
        sudo pip install platformio
        platformio update
    - name: Build firmware
      run: |
        platformio run
